# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityGridPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('where', models.CharField(default='Austin, TX', max_length=200)),
                ('page', models.CharField(default='1', max_length=200)),
                ('rpp', models.CharField(default='20', max_length=200)),
                ('sort', models.CharField(default='dist', max_length=200)),
                ('rformat', models.CharField(default='json', max_length=200)),
                ('hasoffers', models.CharField(default='', max_length=200)),
                ('histograms', models.CharField(default='', max_length=200)),
                ('i', models.CharField(default='', max_length=200)),
                ('publishercode', models.CharField(default='10000016118', max_length=200)),
                ('ip', models.CharField(default=('macbook-pro.local', ['d.9.1.7.7.a.e.f.f.f.9.8.c.5.6.f.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa'], ['fe80::f65c:89ff:fea7:719d']), max_length=1000)),
                ('id_type', models.CharField(default='cs', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('customer_only', models.CharField(default='', max_length=200)),
                ('all_results', models.CharField(default='', max_length=200)),
                ('review_count', models.CharField(default='', max_length=200)),
                ('placement', models.CharField(default='', max_length=200)),
                ('callback', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
